--- 
comments: 
  appid: 1792738694148588
  colorscheme: light
  facebook: ~
  num_posts: 10
  order_by: reverse_time
defaults: 
  - 
    scope: 
      path: ""
      type: posts
    values: 
      comments: true
markdown: kramdown
name: "Jeremy Erwin"
permalink: "/blog/:year/:month/:day/:title"
