name: Jeremy Erwin
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
comments : 
	facebook :
		appid : 1792738694148588
		num_posts : 10
		colorscheme: "light"
		order_by : "reverse_time"
  
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      comments: true
